### ISSUE TITLE
 std::io::Read input 

### ISSUE THREAD

**Issue by 89z** [zS1L3NT/rs-parson#1]
If I have a reader input, for example coming from a HTTP request, can I JSON parse from the reader directly?

or do I have to read into a string first? It seems that for larger inputs, it could be more efficient to parse JSON from reader directly

**Comment by zS1L3NT** [comment]
For now all parsing is done as a string...

**Comment by 89z** [comment]
I found workaround:

https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html
