### ISSUE TITLE
to_string with indent

### ISSUE THREAD

**Issue by 89z** [zS1L3NT/rs-parson#2]
I would like something like this:

~~~json
{
   "month": 12,
   "day": 31
}
~~~

is it possible?

<https://docs.rs/parson/latest/parson/struct.JSONValue.html#method.to_string>

**Comment by zS1L3NT** [comment]
I can implement that, give me a while!

**Comment by zS1L3NT** [comment]
Update your dependency to version 1.1.0
https://github.com/zS1L3NT/rs-parson/releases/tag/v1.1.0

A new method exists for formatting JSON, `.format_string(indents, spaces)`. Let me know if there are any other issues

**Comment by 89z** [comment]
thank you!
