### ISSUE TITLE
link to docs

### ISSUE THREAD

**Issue by 89z** [zS1L3NT/rs-parson#3]
https://docs.rs/parson

**Comment by zS1L3NT** [comment]
Hello, I don't understand the purpose of this issue. Please follow the issue template [here](https://github.com/zS1L3NT/rs-parson/issues/new/choose) when creating an issue on this repository

**Comment by 89z** [comment]
this link:

https://docs.rs/parson

should be somewhere in this repo, like here:

https://github.com/zS1L3NT/rs-parson/blob/main/README.md
